package Euro;


/**
* Euro/Eur.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Euro.idl
* Tuesday, February 18, 2025 6:31:22 PM WAT
*/

public interface Eur extends EurOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Eur
