package Euro;


/**
* Euro/EurHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Euro.idl
* Tuesday, February 18, 2025 6:31:22 PM WAT
*/

abstract public class EurHelper
{
  private static String  _id = "IDL:Euro/Eur:1.0";

  public static void insert (org.omg.CORBA.Any a, Euro.Eur that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Euro.Eur extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Euro.EurHelper.id (), "Eur");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Euro.Eur read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_EurStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Euro.Eur value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Euro.Eur narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Euro.Eur)
      return (Euro.Eur)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Euro._EurStub stub = new Euro._EurStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Euro.Eur unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Euro.Eur)
      return (Euro.Eur)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Euro._EurStub stub = new Euro._EurStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
