package Euro;

/**
* Euro/EurHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Euro.idl
* Tuesday, February 18, 2025 6:31:22 PM WAT
*/

public final class EurHolder implements org.omg.CORBA.portable.Streamable
{
  public Euro.Eur value = null;

  public EurHolder ()
  {
  }

  public EurHolder (Euro.Eur initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Euro.EurHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Euro.EurHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Euro.EurHelper.type ();
  }

}
