package Euro;


/**
* Euro/EurOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Euro.idl
* Tuesday, February 18, 2025 6:31:22 PM WAT
*/

public interface EurOperations 
{
  String devise ();
  void devise (String newDevise);
  double taux ();
  void taux (double newTaux);
  double toEuro (double devise);
  double toDevise (double euro);
  void setTaux (double _taux);
  void setDevise (String _devise);
} // interface EurOperations
