package Euro;


/**
* Euro/EurPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Euro.idl
* Tuesday, February 18, 2025 6:31:22 PM WAT
*/

public abstract class EurPOA extends org.omg.PortableServer.Servant
 implements Euro.EurOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("_get_devise", new java.lang.Integer (0));
    _methods.put ("_set_devise", new java.lang.Integer (1));
    _methods.put ("_get_taux", new java.lang.Integer (2));
    _methods.put ("_set_taux", new java.lang.Integer (3));
    _methods.put ("toEuro", new java.lang.Integer (4));
    _methods.put ("toDevise", new java.lang.Integer (5));
    _methods.put ("setTaux", new java.lang.Integer (6));
    _methods.put ("setDevise", new java.lang.Integer (7));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Euro/Eur/_get_devise
       {
         String $result = null;
         $result = this.devise ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // Euro/Eur/_set_devise
       {
         String newDevise = in.read_string ();
         this.devise (newDevise);
         out = $rh.createReply();
         break;
       }

       case 2:  // Euro/Eur/_get_taux
       {
         double $result = (double)0;
         $result = this.taux ();
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       case 3:  // Euro/Eur/_set_taux
       {
         double newTaux = in.read_double ();
         this.taux (newTaux);
         out = $rh.createReply();
         break;
       }

       case 4:  // Euro/Eur/toEuro
       {
         double devise = in.read_double ();
         double $result = (double)0;
         $result = this.toEuro (devise);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       case 5:  // Euro/Eur/toDevise
       {
         double euro = in.read_double ();
         double $result = (double)0;
         $result = this.toDevise (euro);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       case 6:  // Euro/Eur/setTaux
       {
         double _taux = in.read_double ();
         this.setTaux (_taux);
         out = $rh.createReply();
         break;
       }

       case 7:  // Euro/Eur/setDevise
       {
         String _devise = in.read_string ();
         this.setDevise (_devise);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Euro/Eur:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Eur _this() 
  {
    return EurHelper.narrow(
    super._this_object());
  }

  public Eur _this(org.omg.CORBA.ORB orb) 
  {
    return EurHelper.narrow(
    super._this_object(orb));
  }


} // class EurPOA
